/**
 * Brute-force and CPU-exhaustion protection for `/api/auth/*`.
 *
 * SCOPE AND DURABILITY — read before relying on this.
 *
 * Every counter here lives in a plain `Map` inside a single Node process.
 * That means:
 *
 *   - State is lost on restart. A redeploy resets every block.
 *   - State is NOT shared between processes. If this server is ever run as
 *     more than one process, each one enforces its own independent budget,
 *     and the effective limit multiplies by the process count.
 *   - There is no coordination, no replication, and no persistence.
 *
 * This repo runs a single server process and has no multi-process
 * coordination anywhere, so per-process enforcement is the honest ceiling
 * today. Do not describe this as cluster-wide or distributed rate limiting.
 * Moving to multiple processes requires shared storage before these limits
 * mean anything.
 *
 * WHAT THIS DOES NOT COVER
 *
 * A distributed attack that guesses one account's password from many source
 * IPs is deliberately not blocked. See `loginPerIpEmail` below for why: a
 * global per-email lockout would let an attacker lock a victim out of their
 * own account, which is a worse failure than the one it prevents.
 */

/** Reason a request was denied, for logging and tests. */
export type AuthThrottleScope = 'ip' | 'ip+email' | 'concurrency';

export type AuthThrottleDecision =
  | { allowed: true }
  | {
      allowed: false;
      retryAfterSeconds: number;
      scope: AuthThrottleScope;
    };

export type AuthRateLimiterOptions = {
  /** Injectable clock. Tests drive this instead of sleeping. */
  now?: () => number;
  /**
   * Hard cap on tracked keys, so that an attacker rotating emails or spoofing
   * source addresses cannot grow these maps without bound. Exceeding it evicts
   * expired entries first, then the oldest remaining ones.
   */
  maxTrackedKeys?: number;
};

type Bucket = {
  /** Failures counted inside the current window. */
  failures: number;
  /** Epoch ms when the current counting window closes. */
  windowEndsAt: number;
  /** Epoch ms until which the key is blocked outright, or 0 when not blocked. */
  blockedUntil: number;
};

type BucketPolicy = {
  /** Failures allowed inside one window before the key is blocked. */
  maxFailures: number;
  /** Length of the counting window, in ms. */
  windowMs: number;
  /** How long a key stays blocked once it trips, in ms. */
  blockMs: number;
};

const MINUTE_MS = 60_000;

/**
 * Tight bucket, keyed on source IP *and* the submitted email together.
 *
 * Keying on the pair rather than on the email alone is deliberate. A global
 * per-email counter would let anyone lock a victim out of their own account
 * just by submitting bad passwords for that address. Because this bucket also
 * includes the source IP, failures generated by an attacker elsewhere never
 * touch the bucket the real user is authenticating through.
 *
 * The cost of that choice is stated at the top of this file: a many-IP
 * distributed guessing attack on a single account is not stopped here.
 */
const loginPerIpEmail: BucketPolicy = {
  maxFailures: 5,
  windowMs: 15 * MINUTE_MS,
  blockMs: 15 * MINUTE_MS,
};

/**
 * Looser bucket keyed on source IP alone. Catches password spraying, where one
 * host tries a few passwords each against many different accounts and so never
 * trips the per-pair bucket.
 *
 * The threshold is deliberately generous because shared NATs, VPNs, and CGNAT
 * put many unrelated users behind one address; this should bite an attacker
 * long before it bites an office.
 */
const loginPerIp: BucketPolicy = {
  maxFailures: 30,
  windowMs: 15 * MINUTE_MS,
  blockMs: 15 * MINUTE_MS,
};

/**
 * Registration is throttled per IP because it runs the same expensive scrypt
 * hash as login and creates rows. Every attempt counts here, not just failures,
 * since a successful registration is exactly what abuse wants to repeat.
 */
const registerPerIp: BucketPolicy = {
  maxFailures: 5,
  windowMs: 60 * MINUTE_MS,
  blockMs: 60 * MINUTE_MS,
};

export class AuthRateLimiter {
  private readonly buckets = new Map<string, Bucket>();
  private readonly now: () => number;
  private readonly maxTrackedKeys: number;

  constructor(options: AuthRateLimiterOptions = {}) {
    this.now = options.now ?? Date.now;
    this.maxTrackedKeys = options.maxTrackedKeys ?? 10_000;
  }

  /**
   * Decide whether a login attempt may run at all. Call this *before* doing any
   * password hashing — the point is to reject before spending CPU.
   */
  checkLogin(params: { email: string; ip: string }): AuthThrottleDecision {
    const pair = this.check(
      this.pairKey(params.ip, params.email),
      loginPerIpEmail,
    );

    if (!pair.allowed) {
      return pair;
    }

    return this.check(this.ipKey('login', params.ip), loginPerIp);
  }

  /**
   * Record a failed login. Only call this for an attempt that actually ran and
   * was rejected on credentials.
   *
   * Attempts denied by `checkLogin` must NOT be recorded: counting them would
   * let an attacker who keeps hammering a blocked key extend that block
   * forever, which would turn the limiter into the lockout weapon it is
   * designed to avoid.
   */
  recordLoginFailure(params: { email: string; ip: string }): void {
    this.recordFailure(this.pairKey(params.ip, params.email), loginPerIpEmail);
    this.recordFailure(this.ipKey('login', params.ip), loginPerIp);
  }

  /**
   * Clear the tight bucket after a proven-legitimate login, so that a user who
   * mistyped a few times and then succeeded starts clean.
   *
   * The per-IP bucket is intentionally left alone: one successful login must
   * not wipe the evidence of spraying against many other accounts from the
   * same host.
   */
  recordLoginSuccess(params: { email: string; ip: string }): void {
    this.buckets.delete(this.pairKey(params.ip, params.email));
  }

  checkRegister(params: { ip: string }): AuthThrottleDecision {
    return this.check(this.ipKey('register', params.ip), registerPerIp);
  }

  /** Registration counts every attempt, successful or not. */
  recordRegisterAttempt(params: { ip: string }): void {
    this.recordFailure(this.ipKey('register', params.ip), registerPerIp);
  }

  /** Exposed for tests and diagnostics; not part of the request path. */
  get trackedKeyCount(): number {
    return this.buckets.size;
  }

  private check(key: string, policy: BucketPolicy): AuthThrottleDecision {
    const now = this.now();
    const bucket = this.buckets.get(key);

    if (!bucket) {
      return { allowed: true };
    }

    if (bucket.blockedUntil > now) {
      return {
        allowed: false,
        retryAfterSeconds: Math.max(
          1,
          Math.ceil((bucket.blockedUntil - now) / 1000),
        ),
        scope: policy === loginPerIpEmail ? 'ip+email' : 'ip',
      };
    }

    // The block has aged out, or the counting window closed with the key still
    // under its budget. Either way the key gets a clean slate.
    if (bucket.blockedUntil > 0 || bucket.windowEndsAt <= now) {
      this.buckets.delete(key);
    }

    return { allowed: true };
  }

  private recordFailure(key: string, policy: BucketPolicy): void {
    const now = this.now();
    const existing = this.buckets.get(key);

    // A currently-blocked key is left completely untouched. Recording against
    // it would either clear the block or push its expiry further out, and both
    // are wrong: a blocked key must serve exactly the penalty it earned, no
    // more and no less. Callers are expected not to record denied attempts,
    // but the invariant is enforced here so it cannot depend on that.
    if (existing && existing.blockedUntil > now) {
      return;
    }

    const bucket: Bucket =
      existing && existing.blockedUntil === 0 && existing.windowEndsAt > now
        ? existing
        : { blockedUntil: 0, failures: 0, windowEndsAt: now + policy.windowMs };

    bucket.failures += 1;

    if (bucket.failures >= policy.maxFailures) {
      bucket.blockedUntil = now + policy.blockMs;
    }

    // Re-insert so Map iteration order approximates least-recently-written,
    // which is what the overflow eviction below relies on.
    this.buckets.delete(key);
    this.buckets.set(key, bucket);
    this.enforceCapacity();
  }

  private enforceCapacity(): void {
    if (this.buckets.size <= this.maxTrackedKeys) {
      return;
    }

    const now = this.now();

    for (const [key, bucket] of this.buckets) {
      if (bucket.blockedUntil <= now && bucket.windowEndsAt <= now) {
        this.buckets.delete(key);
      }
    }

    // Still over budget after dropping dead entries: evict oldest-written keys
    // until back under the cap. This can drop a live block, which is the
    // correct trade — an unbounded map is a memory-exhaustion vector, and the
    // cap is far above any legitimate working set.
    for (const key of this.buckets.keys()) {
      if (this.buckets.size <= this.maxTrackedKeys) {
        break;
      }

      this.buckets.delete(key);
    }
  }

  private pairKey(ip: string, email: string): string {
    return `login:${ip} ${this.normalizeEmail(email)}`;
  }

  private ipKey(prefix: 'login' | 'register', ip: string): string {
    return `${prefix}-ip:${ip}`;
  }

  private normalizeEmail(email: string): string {
    return email.trim().toLowerCase();
  }
}

/**
 * Bounds how many password hashes may run at once.
 *
 * Failure counting alone does not stop CPU exhaustion: a few hundred
 * *first* attempts from fresh keys are all individually under every limit
 * above, yet each one occupies a libuv threadpool slot doing scrypt work and
 * together they stall the event loop for everyone.
 *
 * This gate is what actually protects the process. It rejects immediately
 * rather than queueing, because a queued request still holds a socket and
 * memory — the very resources under attack.
 *
 * Per-process, like everything else in this file.
 */
export class PasswordHashConcurrencyGate {
  private inFlight = 0;

  constructor(private readonly maxConcurrent = 8) {}

  tryAcquire(): boolean {
    if (this.inFlight >= this.maxConcurrent) {
      return false;
    }

    this.inFlight += 1;
    return true;
  }

  release(): void {
    this.inFlight = Math.max(0, this.inFlight - 1);
  }

  /** Exposed for tests; not part of the request path. */
  get inFlightCount(): number {
    return this.inFlight;
  }
}

/** Denial payload shared by both gates, so handlers stay uniform. */
export const authThrottleMessage =
  'Too many authentication attempts. Try again later.';
